# Generated by Django 3.0 on 2020-01-05 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itemManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lastUsed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
