# Generated by Django 3.0.3 on 2020-02-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemManagement', '0005_auto_20200128_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kghID',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
