# Generated by Django 3.0.3 on 2020-03-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemManagement', '0007_auto_20200224_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='data',
            field=models.BinaryField(),
        ),
    ]
