# Generated by Django 3.0.4 on 2020-03-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemManagement', '0008_auto_20200326_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order']},
        ),
    ]
