# Generated by Django 2.2.7 on 2020-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemManagement', '0010_auto_20200401_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='needToNotifyAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
