# Generated by Django 2.2.7 on 2020-04-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemManagement', '0011_item_needtonotifyadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='needToNotifyAdmin',
        ),
    ]
