# Generated by Django 3.0.4 on 2020-04-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemManagement', '0012_remove_item_needtonotifyadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alertWhenLow',
            field=models.BooleanField(default=False),
        ),
    ]
