# Generated by Django 3.0.4 on 2020-04-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemManagement', '0013_item_alertwhenlow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='alertThreshold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
