language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv sync
  - npm ci
  - ./node_modules/.bin/webpack --config webpack.config.js --mode=production
# command to run tests
script:
  - pipenv run python manage.py test
