#!/bin/bash
MJML_FOLDER="emails/mjml"
RENDER_FOLDER="emails/templates"

# ARG_OPTIONAL_BOOLEAN([watch],[],[Watches for changes in MJML files])
# ARG_HELP([Compiles the MJML emails])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die()
{
	local _ret=$2
	test -n "$_ret" || _ret=1
	test "$_PRINT_HELP" = yes && print_help >&2
	echo "$1" >&2
	exit ${_ret}
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_watch="off"


print_help()
{
	printf '%s\n' "Compiles the MJML emails"
	printf 'Usage: %s [--(no-)watch] [-h|--help]\n' "$0"
	printf '\t%s\n' "--watch, --no-watch: Watches for changes in MJML files (off by default)"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			--no-watch|--watch)
				_arg_watch="on"
				test "${1:0:5}" = "--no-" && _arg_watch="off"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

mkdir -p "$RENDER_FOLDER"

if [ "$_arg_watch" == "on" ]; then
    mjml_options="--watch"
fi
./node_modules/.bin/mjml $mjml_options "$MJML_FOLDER"/*.mjml -o "$RENDER_FOLDER"

# ] <-- needed because of Argbash