# Generated by Django 2.2.7 on 2020-02-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='fname lname', max_length=100),
        ),
    ]
