# Generated by Django 2.2.7 on 2020-02-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20200203_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
