# Generated by Django 3.0.3 on 2020-04-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20200223_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleteFlag',
            new_name='deleted',
        ),
    ]
