# Generated by Django 2.2.7 on 2020-02-25 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='target_user',
        ),
        migrations.AddField(
            model_name='userlogs',
            name='target_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject', to=settings.AUTH_USER_MODEL),
        ),
    ]
