# Generated by Django 2.2.7 on 2020-02-25 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20200225_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='target_user',
            field=models.ManyToManyField(blank=True, related_name='subject', to=settings.AUTH_USER_MODEL),
        ),
    ]
