# Generated by Django 2.2.7 on 2020-02-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20200225_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='logMsg',
            field=models.CharField(max_length=1024),
        ),
    ]
