# Generated by Django 2.2.7 on 2020-02-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20200225_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcountlogs',
            old_name='user',
            new_name='operator_user',
        ),
        migrations.RenameField(
            model_name='iteminfologs',
            old_name='user',
            new_name='operator_user',
        ),
        migrations.RenameField(
            model_name='userlogs',
            old_name='user',
            new_name='operator_user',
        ),
        migrations.RenameField(
            model_name='userlogs',
            old_name='target_user',
            new_name='subject_user',
        ),
    ]
