# Generated by Django 2.2.7 on 2020-03-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0006_auto_20200225_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='subject_user',
        ),
        migrations.AddField(
            model_name='userlogs',
            name='subject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to=settings.AUTH_USER_MODEL),
        ),
    ]
