# Generated by Django 3.0.3 on 2020-04-28 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0008_auto_20200401_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=1024)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('arg1', models.CharField(db_index=True, max_length=200, null=True)),
                ('arg2', models.CharField(db_index=True, max_length=200, null=True)),
                ('arg3', models.CharField(db_index=True, max_length=200, null=True)),
                ('arg4', models.CharField(db_index=True, max_length=200, null=True)),
                ('arg5', models.CharField(db_index=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='iteminfologs',
            name='item',
        ),
        migrations.RemoveField(
            model_name='iteminfologs',
            name='operator_user',
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='operator_user',
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='subject_user',
        ),
        migrations.DeleteModel(
            name='ItemCountLogs',
        ),
        migrations.DeleteModel(
            name='ItemInfoLogs',
        ),
        migrations.DeleteModel(
            name='UserLogs',
        ),
    ]
